/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Bittor
 */
public class PropIniFrame extends javax.swing.JFrame {

    /**
     * Creates new form propIni
     */
    public PropIniFrame(InitiativeListener listener) {
    	this.listener = listener;
        initComponents();
    }
    
    public interface InitiativeListener{
		void proponerIniciativa(String nombre, String fecha, String lugar, String descr, String hora);
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
  	
        header = new javax.swing.JLabel();
        ucmIcon = new javax.swing.JLabel();
        titActiv = new javax.swing.JLabel();
        lugActiv = new javax.swing.JLabel();
        fechAct = new javax.swing.JLabel();
        descrAct = new javax.swing.JLabel();
        tituloField = new javax.swing.JTextField();
        lugarField = new javax.swing.JTextField();
        fechaField = new javax.swing.JTextField();
        iniDescrArea = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        proponerButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        horaField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(384, 620, 384, 620));
        setResizable(false);

        header.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bittor\\git\\IS\\Complutensers\\src\\resources\\header.jpg")); // NOI18N

        ucmIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bittor\\git\\IS\\Complutensers\\src\\resources\\ucm.png")); // NOI18N

        titActiv.setText("Título de actividad");

        lugActiv.setText("Lugar de actividad");

        fechAct.setText("Fecha (dd/mm/aaaa)");

        descrAct.setText("Descripción del evento");

        tituloField.setText("Introduzca el título...");

        lugarField.setText("Introduzca el lugar...");

        fechaField.setText("Introduzca la fecha...");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        iniDescrArea.setViewportView(jTextArea1);

        proponerButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bittor\\git\\IS\\Complutensers\\src\\resources\\initiatives.png")); // NOI18N

        jLabel1.setText("Hora:");

        horaField.setText("hh:mm");
        
        proponerButton.addActionListener((e)->{
        	listener.proponerIniciativa(tituloField.getText(),fechaField.getText(),lugarField.getText(),jTextArea1.getText(),horaField.getText());        	
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(ucmIcon))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iniDescrArea, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descrAct)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lugActiv)
                            .addComponent(fechAct)
                            .addComponent(titActiv))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituloField, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(33, 33, 33)
                                    .addComponent(horaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fechaField, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                    .addComponent(lugarField)))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(proponerButton))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header)
                .addGap(18, 18, 18)
                .addComponent(ucmIcon)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titActiv)
                    .addComponent(tituloField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lugActiv)
                    .addComponent(lugarField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechAct)
                    .addComponent(fechaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descrAct)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(horaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(iniDescrArea, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(proponerButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    // Variables declaration - do not modify                     
    private javax.swing.JLabel descrAct;
    private javax.swing.JLabel fechAct;
    private javax.swing.JTextField fechaField;
    private javax.swing.JLabel header;
    private javax.swing.JScrollPane iniDescrArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField horaField;
    private javax.swing.JLabel lugActiv;
    private javax.swing.JTextField lugarField;
    private javax.swing.JButton proponerButton;
    private javax.swing.JLabel titActiv;
    private javax.swing.JTextField tituloField;
    private javax.swing.JLabel ucmIcon;
    private InitiativeListener listener;
    // End of variables declaration                   
}
